### ISSUE TITLE
Meta tags for Twitter and Facebook

### ISSUE THREAD

**Issue by tomchen** [arcomage/arcomage-hd#58]
- [x] ogimage not shown
- [x] Meta tags (Open Graph) for [Twitter](https://cards-dev.twitter.com/validator) and [Facebook](https://developers.facebook.com/tools/debug/)
- [x] in order to update image cache on Twitter, add `?<FILEHASH>` to the URL
